### ISSUE TITLE
eval_utils.py hangs at dataloader

### ISSUE THREAD

**Issue by weijiawang96** [CVMI-Lab/ST3D#23]
Hi, 

My test.py used to work, but I once pressed Ctrl+C during testing, and then when I run test.py again, the program hangs on this line (line 54 in eval_utils.py):
`for i, batch_dict in enumerate(dataloader):`

I really don't know where the deadlock was created. Lowering num_workers does not help.

The command I ran was:
`python test.py --cfg_file ./cfgs/da-nuscenes-kitti_models/pvrcnn/pvrcnn_old_anchor.yaml --batch_size 4 --ckpt ./cfgs/da-nuscenes-kitti_models/pvrcnn/ckpt_pvrcnn_source_only.pth`

And it hangs at this step (epoch 0 will never proceed):
eval:   0%|                                                                                                                                         | 0/943 [00:00<?, ?it/s]

When I press Ctrl+C, it says so:

[2021-10-04 17:02:27,446  eval_utils.py 40  INFO]  *************** EPOCH 3 EVALUATION *****************
eval:   0%|                                                                                                                                                                                                | 0/943 [00:00<?, ?it/s]^CTraceback (most recent call last):
  File "test.py", line 214, in <module>
    main()
  File "test.py", line 210, in main
    epoch_id, dist_test=dist_test)
  File "test.py", line 64, in eval_single_ckpt
    result_dir=eval_output_dir, save_to_file=args.save_to_file, args=args
  File "/home/wangweijia/Desktop/UDA/ST3D/tools/eval_utils/eval_utils.py", line 54, in eval_one_epoch
    for i, batch_dict in enumerate(dataloader):
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1024, in _get_data
    success, data = self._try_get_data()
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "/home/wangweijia/anaconda3/envs/st3d/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
eval:   0%|   

I believe a deadlock is created somewhere, can you offer some help? I really appreciate it!

**Comment by weijiawang96** [comment]
I see what may have happened. When I pressed Ctrl + C, despite the python program stops (and I quitted my IDE), it seems that some processes were still running at the background, silently. Now my test.py works fine, after I waited for 1 hour or so. I'm closing this, and sorry for any disruption!
